version: '3.8'

# Jaringan kustom untuk memungkinkan semua layanan berkomunikasi
networks:
  monitoring-net:
    driver: bridge

services:
  # Layanan pertama: Aplikasi React dan Nginx
  # Container ini akan dibangun dari Dockerfile yang Anda sediakan.
  react-nginx-app:
    build:
      # Tentukan direktori tempat Dockerfile dan file proyek lainnya berada.
      context: .
      dockerfile: Dockerfile
    container_name: react-nginx-app
    restart: unless-stopped
    ports:
      # Port untuk mengakses aplikasi React melalui Nginx
      - "80:80"
      # Port untuk mengakses metrik Prometheus Exporter dari Nginx
      - "9113:9113"
    networks:
      - monitoring-net

  # Layanan kedua: Prometheus Server
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      # Memasang file konfigurasi Prometheus lokal Anda
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring-net

  # Layanan ketiga: Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-net

volumes:
  grafana-data:
