# prometheus.yml
global:
  # Atur interval scraping global ke 15 detik.
  # Ini adalah frekuensi Prometheus mengambil metrik.
  scrape_interval: 15s

scrape_configs:
  # Job untuk memantau Prometheus itu sendiri.
  - job_name: 'prometheus'
    # Prometheus mengambil metrik dari dirinya sendiri di localhost:9090.
    static_configs:
      - targets: ['localhost:9090']

  # Job untuk memantau Nginx Prometheus Exporter dari aplikasi React.
  # Layanan ini akan berjalan di container 'react-nginx-app' yang didefinisikan di docker-compose.yml.
  - job_name: 'react-nginx-exporter'
    # Ganti 'react-nginx-app' dengan nama layanan yang Anda gunakan di docker-compose.yml
    # Prometheus akan mencari container ini dan mengambil metrik dari port 9113.
    static_configs:
      - targets: ['react-nginx-app:9113']
