name: CI/CD Pipeline

on:
  push:
    branches:
      - main # This workflow runs on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Docker image to Artifact Registry
        run: |
          # Configure Docker for Artifact Registry
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
          
          # Build and tag the Docker image. Assumes your React app is in a 'client' folder.
          docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fullstak-repo/cloud-app:latest ./client
          
          # Push the image to Artifact Registry
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fullstak-repo/cloud-app:latest

      - name: Deploy to Compute Engine
        run: |
          # Set up the SSH private key
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCE_IP }} >> ~/.ssh/known_hosts

          # Execute the deployment script on the VM via SSH
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no khali@${{ secrets.GCE_IP }} "
            # Log in to Artifact Registry on the VM
            gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
            
            # Pull the latest Docker image
            docker pull asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fullstak-repo/cloud-app:latest
            
            # Stop and remove the old container
            docker stop fullstak-app || true
            docker rm fullstak-app || true
            
            # Run a new container
            docker run -d --name fullstak-app -p 80:80 asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fullstak-repo/cloud-app:latest
          "
