# Nama workflow ini yang akan muncul di tab "Actions" di GitHub
name: Deploy to Google Compute Engine

# Tentukan pemicu (trigger) untuk workflow ini
on:
  push:
    branches:
      - main  # Workflow akan berjalan setiap kali ada push ke branch 'main'

# Definisi job yang akan dijalankan
jobs:
  build-and-deploy:
    # Tentukan environment untuk job
    runs-on: ubuntu-latest

    # Langkah-langkah (steps) yang akan dijalankan
    steps:
      - name: Checkout Kode dari Repository
        uses: actions/checkout@v2

      - name: Siapkan Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: fullstak-project
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build dan Push Docker Image ke Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
          
          # Perintah build telah dikoreksi. Tanda titik '.' menunjukkan konteks build
          # adalah root repositori, di mana folder 'public' dan 'src' berada.
          docker build -t asia-southeast2-docker.pkg.dev/fullstak-project/fullstak-repo/cloud-app:latest .
          
          docker push asia-southeast2-docker.pkg.dev/fullstak-project/fullstak-repo/cloud-app:latest

      - name: Deploy ke Google Compute Engine
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.101.235.208 >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no khali@34.101.235.208 "
            gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
            
            docker pull asia-southeast2-docker.pkg.dev/fullstak-project/fullstak-repo/cloud-app:latest
            
            docker stop fullstak-app || true
            docker rm fullstak-app || true
            
            docker run -d --name fullstak-app -p 80:80 asia-southeast2-docker.pkg.dev/fullstak-project/fullstak-repo/cloud-app:latest
          "
