name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Jalankan workflow setiap kali ada push ke branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Docker image to Artifact Registry
        run: |
          # Konfigurasi Docker untuk Artifact Registry
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
          
          # Build dan beri tag pada Docker image
          docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fullstak-repo/cloud-app:latest ./client
          
          # Unggah image ke Artifact Registry
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fullstak-repo/cloud-app:latest

      - name: Set up SSH key for GCE
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Compute Engine
        run: |
          # Jalankan skrip deploy di VM
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no khali@${{ secrets.GCE_IP }} "
            # Login ke Artifact Registry di VM
            gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
            
            # Pull image terbaru
            docker pull asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fullstak-repo/cloud-app:latest
            
            # Hentikan dan hapus container lama
            docker stop fullstak-app || true
            docker rm fullstak-app || true
            
            # Jalankan container baru
            docker run -d --name fullstak-app -p 80:80 asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fullstak-repo/cloud-app:latest
          "
