name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: fullstak-project
  AR_REPO_LOCATION: asia-southeast2
  AR_REPO_NAME: fullstak-repo
  IMAGE_NAME: frontend
  CLOUD_RUN_SERVICE: fullstak-service
  CLOUD_RUN_REGION: asia-southeast2
  GCP_SA_EMAIL: github-actions-sa@fullstak-project.iam.gserviceaccount.com
  INSTANCE_IP: 35.219.48.23

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Configure Docker
        run: gcloud auth configure-docker ${AR_REPO_LOCATION}-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t ${AR_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO_NAME}/${IMAGE_NAME}:${{ github.sha }} .
          docker push ${AR_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO_NAME}/${IMAGE_NAME}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${CLOUD_RUN_SERVICE} \
            --image=${AR_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO_NAME}/${IMAGE_NAME}:${{ github.sha }} \
            --region=${CLOUD_RUN_REGION} \
            --platform=managed \
            --allow-unauthenticated \
            --ingress=all \
            --port=80 \
            --update-env-vars=GCP_INSTANCE_IP=${INSTANCE_IP}

      - name: Print service URL
        run: gcloud run services describe ${CLOUD_RUN_SERVICE} --region=${CLOUD_RUN_REGION} --format='value(status.url)'
